{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "34d1a01b-7296-4ff1-b19d-444594c8e6c4",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting Faker==22.0.0\n",
      "  Downloading Faker-22.0.0-py3-none-any.whl.metadata (15 kB)\n",
      "Requirement already satisfied: python-dateutil>=2.4 in c:\\users\\gvtit\\appdata\\local\\programs\\python\\python312\\lib\\site-packages (from Faker==22.0.0) (2.9.0.post0)\n",
      "Requirement already satisfied: six>=1.5 in c:\\users\\gvtit\\appdata\\local\\programs\\python\\python312\\lib\\site-packages (from python-dateutil>=2.4->Faker==22.0.0) (1.17.0)\n",
      "Downloading Faker-22.0.0-py3-none-any.whl (1.7 MB)\n",
      "   ---------------------------------------- 0.0/1.7 MB ? eta -:--:--\n",
      "   ---------------------------------------- 0.0/1.7 MB ? eta -:--:--\n",
      "   ------ --------------------------------- 0.3/1.7 MB ? eta -:--:--\n",
      "   ------------ --------------------------- 0.5/1.7 MB 929.6 kB/s eta 0:00:02\n",
      "   ------------ --------------------------- 0.5/1.7 MB 929.6 kB/s eta 0:00:02\n",
      "   ------------------ --------------------- 0.8/1.7 MB 644.9 kB/s eta 0:00:02\n",
      "   ------------------ --------------------- 0.8/1.7 MB 644.9 kB/s eta 0:00:02\n",
      "   ------------------ --------------------- 0.8/1.7 MB 644.9 kB/s eta 0:00:02\n",
      "   ------------------------ --------------- 1.0/1.7 MB 592.2 kB/s eta 0:00:02\n",
      "   ------------------------ --------------- 1.0/1.7 MB 592.2 kB/s eta 0:00:02\n",
      "   ------------------------------ --------- 1.3/1.7 MB 610.0 kB/s eta 0:00:01\n",
      "   ------------------------------------ --- 1.6/1.7 MB 630.8 kB/s eta 0:00:01\n",
      "   ---------------------------------------- 1.7/1.7 MB 651.9 kB/s eta 0:00:00\n",
      "Installing collected packages: Faker\n",
      "Successfully installed Faker-22.0.0\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "[notice] A new release of pip is available: 25.0.1 -> 25.3\n",
      "[notice] To update, run: python.exe -m pip install --upgrade pip\n"
     ]
    }
   ],
   "source": [
    "!pip install Faker==22.0.0"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "7b41c7ec-50c2-45a3-9978-a3b87ac80981",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Using source CSV: data\\synthetic_invoices.csv\n",
      "Saved realistic noisy dataset -> data\\realistic_invoices.csv\n",
      "\n",
      "Sample rows:\n",
      "\n",
      "                                                                                                                                                                                                                                  text            label\n",
      "                                                                                                                                                          Iw614owell-Mckinney to Du27 ₹1881797.00. amount Ceditn 4981 P issued oPe 1or            other\n",
      "**optino*generatinwholepoor from Johnson LL for invoice #86942 toatl ₹15524.00 due oon 2025-01-25. **optino*generatinwholepoor from Johnson LL for invoice #86942 toatl ₹15524.00 due oon 2025-01-25. Please remiit doraise*at**rrove.   purchase_order\n",
      "                             camera**setdagafour* from Sanchez PLCfori nvoice #54541 ttotal Y264Q6.00 due on 2025-02-28. Pleaser emit* call*situation***. Week real course school everybody operation set others wonder strategy fast. accounts_payable\n",
      "                                                                                                                                                                           Credit noet 2873 issued toG reene Ltd for a9ount ₹31876.00.            other\n",
      "                                       researhc****very** O3dder 60974 received ffor vendor Hensley, Meadoqs and Turner. Qty: 12. Total:₹124789.000. Whatever action themselves center among of hour natural be decide scientist rise.   purchase_order\n",
      "                                                                                                                                                                 Tax inBoice 3516: GST 18% on amount ₹1667.500. Taxable vallue ₹24397.              tax\n",
      "\n",
      "Label distribution:\n",
      "label\n",
      "other               260\n",
      "accounts_payable    256\n",
      "purchase_order      254\n",
      "expense             234\n",
      "tax                 220\n",
      "Name: count, dtype: int64\n"
     ]
    }
   ],
   "source": [
    "# make_realistic.py\n",
    "\"\"\"\n",
    "Create a more realistic, noisy invoice dataset from your existing synthetic CSV.\n",
    "Output: data/realistic_invoices.csv\n",
    "\"\"\"\n",
    "\n",
    "import os, random, re\n",
    "import pandas as pd\n",
    "from pathlib import Path\n",
    "from faker import Faker\n",
    "fake = Faker()\n",
    "\n",
    "# helper functions to add noise / typos / OCR artifacts\n",
    "def random_typo(s, p=0.08):\n",
    "    # with probability p per character, do a random edit (swap/delete/replace)\n",
    "    s = list(s)\n",
    "    i = 0\n",
    "    while i < len(s):\n",
    "        if random.random() < p:\n",
    "            op = random.choice(['swap','del','replace','dup'])\n",
    "            if op == 'swap' and i < len(s)-1:\n",
    "                s[i], s[i+1] = s[i+1], s[i]\n",
    "                i += 2\n",
    "                continue\n",
    "            elif op == 'del':\n",
    "                s.pop(i)\n",
    "                continue\n",
    "            elif op == 'replace':\n",
    "                s[i] = random.choice('abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789')\n",
    "            elif op == 'dup':\n",
    "                s.insert(i, s[i])\n",
    "                i += 1\n",
    "        i += 1\n",
    "    return ''.join(s)\n",
    "\n",
    "def ocr_artifacts(s, p_linebreak=0.03, p_gibberish=0.02):\n",
    "    # insert random breaks or small gibberish tokens\n",
    "    if random.random() < p_linebreak:\n",
    "        pos = random.randint(0, max(0, len(s)-1))\n",
    "        s = s[:pos] + '\\n' + s[pos:]\n",
    "    if random.random() < p_gibberish:\n",
    "        pos = random.randint(0, max(0, len(s)-1))\n",
    "        gib = ' '.join([fake.bothify(text='??##') for _ in range(random.randint(1,3))])\n",
    "        s = s[:pos] + ' ' + gib + ' ' + s[pos:]\n",
    "    return s\n",
    "\n",
    "def mask_keywords(s, keywords, p_mask=0.6):\n",
    "    # for each keyword in list, mask it with blanks or synonyms sometimes\n",
    "    for kw in keywords:\n",
    "        if kw.lower() in s.lower() and random.random() < p_mask:\n",
    "            # replace only some occurrences\n",
    "            pattern = re.compile(re.escape(kw), re.IGNORECASE)\n",
    "            repl = lambda m: ''.join(['*' if random.random() < 0.6 else fake.word() for _ in m.group(0)])\n",
    "            s = pattern.sub(repl, s, count=1)\n",
    "    return s\n",
    "\n",
    "def blend_text(a, b):\n",
    "    # create an ambiguous sample blending two texts\n",
    "    parts = []\n",
    "    a_parts = a.split('. ')\n",
    "    b_parts = b.split('. ')\n",
    "    # take some parts from both\n",
    "    for _ in range(max(1, min(4, (len(a_parts)+len(b_parts))//2))):\n",
    "        part = random.choice([random.choice(a_parts), random.choice(b_parts)])\n",
    "        parts.append(part)\n",
    "    return '. '.join(parts)\n",
    "\n",
    "# find a CSV in data/ or project root\n",
    "possible_paths = list(Path('data').glob('*.csv')) + list(Path('.').glob('*.csv'))\n",
    "csv_path = None\n",
    "if possible_paths:\n",
    "    csv_path = possible_paths[0]\n",
    "else:\n",
    "    raise FileNotFoundError(\"No CSV found in project root or data/ — please run the generator step first.\")\n",
    "\n",
    "print(\"Using source CSV:\", csv_path)\n",
    "\n",
    "df = pd.read_csv(csv_path)\n",
    "if 'text' not in df.columns or 'label' not in df.columns:\n",
    "    raise ValueError(f\"CSV must contain 'text' and 'label' columns. Found columns: {df.columns.tolist()}\")\n",
    "\n",
    "random.seed(42)\n",
    "fake.seed_instance(42)\n",
    "\n",
    "keywords_to_mask = ['invoice', 'tax', 'gst', 'po', 'purchase', 'payment', 'reimbursement', 'claim', 'invoice #', 'invoice no', 'po #']\n",
    "\n",
    "rows = []\n",
    "num_samples = len(df)\n",
    "for idx, row in df.iterrows():\n",
    "    text = str(row['text'])\n",
    "    label = row['label']\n",
    "\n",
    "    # 1) sometimes mask obvious invoice keywords\n",
    "    text = mask_keywords(text, keywords_to_mask, p_mask=0.65)\n",
    "\n",
    "    # 2) add OCR-like artifacts and typos\n",
    "    text = ocr_artifacts(text, p_linebreak=0.06, p_gibberish=0.04)\n",
    "    text = random_typo(text, p=0.06)\n",
    "\n",
    "    # 3) randomly append footer / vendor notes (simulate long documents)\n",
    "    if random.random() < 0.18:\n",
    "        extra = fake.sentence(nb_words=random.randint(8,20))\n",
    "        text = text + \" \" + extra\n",
    "\n",
    "    # 4) create ambiguous / blended samples (mix two classes)\n",
    "    if random.random() < 0.12:\n",
    "        other = df.sample(1).iloc[0]['text']\n",
    "        text = blend_text(text, str(other))\n",
    "        # blend label: mark as 'ambiguous' sometimes else keep original\n",
    "        if random.random() < 0.5:\n",
    "            label = random.choice([label, 'other', 'purchase_order', 'accounts_payable'])\n",
    "\n",
    "    # 5) slightly shuffle token order sometimes (to simulate OCR reordering)\n",
    "    if random.random() < 0.08:\n",
    "        tokens = text.split()\n",
    "        random.shuffle(tokens)\n",
    "        text = ' '.join(tokens)\n",
    "\n",
    "    rows.append((text, label))\n",
    "\n",
    "# Add a few completely random \"noise\" samples (junk that sometimes appears on invoices)\n",
    "for _ in range(max(20, int(0.02*num_samples))):\n",
    "    text = fake.paragraph(nb_sentences=random.randint(1,4))\n",
    "    # sometimes include short numeric strings to look like invoice fragments\n",
    "    if random.random() < 0.5:\n",
    "        text += \" \" + \" \".join([str(random.randint(100,99999)) for _ in range(random.randint(1,3))])\n",
    "    label = random.choice(['other', 'expense'])\n",
    "    rows.append((text, label))\n",
    "\n",
    "realistic_df = pd.DataFrame(rows, columns=['text','label'])\n",
    "\n",
    "# shuffle and save\n",
    "realistic_df = realistic_df.sample(frac=1, random_state=42).reset_index(drop=True)\n",
    "os.makedirs('data', exist_ok=True)\n",
    "out_path = Path('data/realistic_invoices.csv')\n",
    "realistic_df.to_csv(out_path, index=False, encoding='utf-8')\n",
    "\n",
    "print(f\"Saved realistic noisy dataset -> {out_path}\")\n",
    "print(\"\\nSample rows:\\n\")\n",
    "print(realistic_df.head(6).to_string(index=False))\n",
    "\n",
    "print(\"\\nLabel distribution:\")\n",
    "print(realistic_df['label'].value_counts())\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "4b26526f-9b40-4918-9a3e-e2ca90a64371",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
